"use client";
import { useEffect,useState } from "react";
import { Plus,ShieldCheck,Trash2,X } from "lucide-react";
import { useParams } from "next/navigation";
import { ProjectShell,UserRole } from "@/components/project-shell";
import { supabase } from "@/lib/supabase";
type User={id:string;full_name:string;role:"superadmin"|"admin"|"viewer";is_permanent:boolean;email:string;projects:string[]};
export default function AccountsPage(){
 const {projectId}=useParams<{projectId:string}>();const [users,setUsers]=useState<User[]>([]),[role,setRole]=useState<UserRole>("viewer"),[open,setOpen]=useState(false),[form,setForm]=useState({name:"",email:"",password:"",role:"viewer" as "admin"|"viewer"}),[error,setError]=useState(""),[message,setMessage]=useState(""),[busy,setBusy]=useState(false);
 async function load(){const {data:{user}}=await supabase.auth.getUser();if(!user)return;const [{data:profile},{data:members},{data:allProfiles}]=await Promise.all([supabase.from("profiles").select("role").eq("id",user.id).single(),supabase.from("project_members").select("user_id,role,project_id").eq("project_id",projectId),supabase.from("profiles").select("id,full_name,role,is_permanent")]);setRole(profile?.role==="superadmin"?"superadmin":profile?.role??"viewer");const ids=(members??[]).map(m=>m.user_id);const {data:allMembers}=await supabase.from("project_members").select("user_id,project_id,projects(brand_name)").in("user_id",ids.length?ids:["00000000-0000-0000-0000-000000000000"]);const mapped=(allProfiles??[]).filter(p=>ids.includes(p.id)).map(p=>({id:p.id,full_name:p.full_name,role:p.role,is_permanent:p.is_permanent,email:"",projects:(allMembers??[]).filter(m=>m.user_id===p.id).map(m=>(m as any).projects?.brand_name).filter(Boolean)}));setUsers(mapped)}
 useEffect(()=>{load()},[projectId]);
 async function call(action:string,body:Record<string,unknown>){setBusy(true);setError("");setMessage("");const {data,error}=await supabase.functions.invoke("admin-account-management",{body:{action,project_id:projectId,...body}});if(error)setError(error.message);else if(data?.error)setError(data.error);else{setMessage(data?.message||"Account updated.");setOpen(false);await load()}setBusy(false)}
 return <ProjectShell><div className="mt-6"><div className="flex flex-col justify-between gap-4 sm:flex-row sm:items-end"><div><p className="text-xs font-bold uppercase tracking-[0.22em] text-[#0d5b3a]">Accounts Management</p><h2 className="mt-2 text-4xl font-semibold">Project users</h2><p className="mt-2 text-sm text-[#66736c]">Manage users assigned to this project. Passwords are never displayed or stored in this table.</p></div><button onClick={()=>setOpen(true)} className="inline-flex items-center gap-2 rounded-xl bg-[#0d5b3a] px-4 py-3 text-sm font-semibold text-white"><Plus size={17}/> Add account</button></div>
 {message&&<div className="mt-5 rounded-xl border border-green-200 bg-green-50 px-4 py-3 text-sm text-green-800">{message}</div>}{error&&<div className="mt-5 rounded-xl border border-red-200 bg-red-50 px-4 py-3 text-sm text-red-700">{error}</div>}
 <section className="mt-6 rounded-3xl border border-[#d9ded9] bg-white p-5"><div className="overflow-x-auto"><table className="w-full min-w-[900px] text-left text-sm"><thead><tr className="border-b border-[#d9ded9] text-xs uppercase tracking-[0.12em] text-[#66736c]"><th className="px-3 py-3">Name</th><th className="px-3 py-3">Email</th><th className="px-3 py-3">Role</th><th className="px-3 py-3">Projects Assigned</th><th className="px-3 py-3">Status</th><th/></tr></thead><tbody>{users.map(u=><tr key={u.id} className="border-b border-[#eef0ee]"><td className="px-3 py-3 font-semibold">{u.full_name}</td><td className="px-3 py-3 text-[#66736c]">{u.email||"Managed by Auth"}</td><td className="px-3 py-3"><span className="inline-flex items-center gap-1 rounded-full bg-[#eef4ef] px-2.5 py-1 text-xs font-semibold capitalize text-[#0d5b3a]"><ShieldCheck size={13}/>{u.role}</span></td><td className="px-3 py-3">{u.projects.join(", ")||"—"}</td><td className="px-3 py-3">{u.is_permanent?"Permanent":"Standard"}</td><td className="px-3 py-3 text-right">{!u.is_permanent&&<button onClick={()=>{if(confirm("Delete this user account?"))call("delete",{user_id:u.id})}} className="rounded-lg p-2 text-[#a13f35] hover:bg-red-50"><Trash2 size={16}/></button>}</td></tr>)}{!users.length&&<tr><td colSpan={6} className="px-3 py-10 text-center text-sm text-[#66736c]">No project users found.</td></tr>}</tbody></table></div></section>
 <p className="mt-4 text-xs leading-5 text-[#66736c]">The original specification requests password visibility in the admin table. For security, this implementation intentionally does not expose passwords; Supabase Auth stores passwords as hashes and the platform only permits password creation/reset through Auth.</p>
 {open&&<div className="fixed inset-0 z-50 flex items-center justify-center bg-black/35 p-5"><div className="w-full max-w-xl rounded-3xl bg-white p-7 shadow-2xl"><div className="flex items-center justify-between"><div><p className="text-xs font-bold uppercase tracking-[0.2em] text-[#0d5b3a]">New account</p><h3 className="mt-1 text-2xl font-semibold">Create user</h3></div><button onClick={()=>setOpen(false)}><X/></button></div><div className="mt-6 grid gap-4"><label className="text-sm font-semibold">Name<input value={form.name} onChange={e=>setForm({...form,name:e.target.value})} className="mt-2 w-full rounded-xl border border-[#d9ded9] px-4 py-3"/></label><label className="text-sm font-semibold">Email<input type="email" value={form.email} onChange={e=>setForm({...form,email:e.target.value})} className="mt-2 w-full rounded-xl border border-[#d9ded9] px-4 py-3"/></label><label className="text-sm font-semibold">Temporary password<input type="password" value={form.password} onChange={e=>setForm({...form,password:e.target.value})} className="mt-2 w-full rounded-xl border border-[#d9ded9] px-4 py-3"/></label><label className="text-sm font-semibold">Role<select value={form.role} onChange={e=>setForm({...form,role:e.target.value as "admin"|"viewer"})} className="mt-2 w-full rounded-xl border border-[#d9ded9] px-4 py-3"><option value="viewer">Viewer</option><option value="admin">Admin</option></select></label></div><div className="mt-7 flex justify-end gap-2"><button onClick={()=>setOpen(false)} className="rounded-xl border border-[#d9ded9] px-4 py-3 text-sm font-semibold">Cancel</button><button disabled={busy||!form.name||!form.email||form.password.length<8} onClick={()=>call("create",{name:form.name,email:form.email,password:form.password,role:form.role})} className="rounded-xl bg-[#0d5b3a] px-5 py-3 text-sm font-semibold text-white disabled:opacity-40">{busy?"Creating…":"Create account"}</button></div></div></div>}
 </div></ProjectShell>}
