"use client";
import { useEffect,useMemo,useState } from "react";
import { Filter } from "lucide-react";
import { useParams } from "next/navigation";
import { ProjectShell } from "@/components/project-shell";
import { MetricChart } from "@/components/metric-chart";
import { supabase } from "@/lib/supabase";
type Row={metric_date:string;topic:string;llm_provider:string;visibility_score:number|null;visibility_rank:number|null;share_of_voice_score:number|null;share_of_voice_rank:number|null;average_position:number|null;average_position_rank:number|null};
const LLMS=["chatgpt","gemini","perplexity","google_ai_overview","claude"],labels:Record<string,string>={chatgpt:"ChatGPT",gemini:"Gemini",perplexity:"Perplexity",google_ai_overview:"Google AI Overview",claude:"Claude"};
export default function AnalyticsPage(){
 const {projectId}=useParams<{projectId:string}>();const [rows,setRows]=useState<Row[]>([]),[topics,setTopics]=useState<string[]>([]),[selectedTopics,setSelectedTopics]=useState<string[]>([]),[selectedLlms,setSelectedLlms]=useState<string[]>(LLMS),[period,setPeriod]=useState("Last 7 Days"),[loading,setLoading]=useState(true),[error,setError]=useState("");
 const start=useMemo(()=>{const d=new Date();d.setHours(0,0,0,0);const days=period==="Today"?0:period==="Last 2 days"?1:period==="Last 14 Days"?13:period==="Last 30 Days"?29:period==="Last 90 Days"?89:period==="All Time"?3650:6;d.setDate(d.getDate()-days);return d.toISOString().slice(0,10)},[period]);
 useEffect(()=>{(async()=>{setLoading(true);const {data:p}=await supabase.from("projects").select("topics").eq("id",projectId).single();const t=p?.topics??[];setTopics(t);setSelectedTopics(v=>v.length?v:t);const {data,error}=await supabase.from("visibility_daily").select("metric_date,topic,llm_provider,visibility_score,visibility_rank,share_of_voice_score,share_of_voice_rank,average_position,average_position_rank").eq("project_id",projectId).neq("llm_provider","Overall").gte("metric_date",start).order("metric_date");if(error)setError(error.message);setRows(data??[]);setLoading(false)})()},[projectId,start]);
 const filtered=rows.filter(r=>(selectedTopics.length===0||selectedTopics.includes(r.topic))&&(selectedLlms.length===0||selectedLlms.includes(r.llm_provider)));
 function aggregate(key:keyof Row){const map=new Map<string,number[]>();for(const r of filtered){const v=r[key];if(typeof v==="number"){const a=map.get(r.metric_date)||[];a.push(v);map.set(r.metric_date,a)}}return [...map.entries()].sort().map(([date,vals])=>({label:new Date(date+"T00:00:00").toLocaleDateString(undefined,{month:"short",day:"numeric"}),value:vals.reduce((a,b)=>a+b,0)/vals.length}))}
 return <ProjectShell><div className="ops-page"><p className="page-eyebrow">Analytics</p><h2 className="page-title mt-1">Detailed analytics</h2><p className="page-description mt-2">Compare visibility, share of voice and average position by answer engine.</p>
 <section className="mt-8 platform-card p-5 sm:p-6"><div className="flex items-start gap-3 pb-4 border-b border-[var(--line)]"><div className="platform-icon"><Filter size={17}/></div><div><h3 className="text-lg font-semibold">Filters</h3><p className="mt-1 text-sm text-[var(--muted-foreground)]">Select the period, topics and answer engines to compare.</p></div></div><div className="pt-4"><div className="flex flex-wrap items-center gap-2"><Filter size={17} className="text-[var(--green)]"/>{["Today","Last 2 Days","Last 7 Days","Last 14 Days","Last 30 Days","Last 90 Days","All Time"].map(p=>{const normalized=p==="Last 2 Days"?"Last 2 days":p;return <button key={p} onClick={()=>setPeriod(normalized)} className={"rounded-xl border px-3 py-2 text-xs font-semibold "+(period===normalized?"border-[var(--green)] bg-[var(--green)] text-white":"border-[var(--line)] bg-white")}>{p}</button>})}</div>
 <div className="mt-4 flex flex-wrap gap-2"><span className="py-2 text-xs font-bold text-[#66736c]">Topics:</span>{topics.map(t=><button key={t} onClick={()=>setSelectedTopics(v=>v.includes(t)?v.filter(x=>x!==t):[...v,t])} className={"rounded-full px-3 py-1.5 text-xs font-semibold "+(selectedTopics.includes(t)?"bg-[#0d5b3a] text-white":"bg-[var(--soft)] text-[var(--green)]")}>{t}</button>)}{topics.length===0&&<span className="py-2 text-xs text-[#66736c]">No topics configured.</span>}</div>
 <div className="mt-3 flex flex-wrap gap-2"><span className="py-2 text-xs font-bold text-[#66736c]">LLMs:</span>{LLMS.map(l=><button key={l} onClick={()=>setSelectedLlms(v=>v.includes(l)?v.filter(x=>x!==l):[...v,l])} className={"rounded-full px-3 py-1.5 text-xs font-semibold "+(selectedLlms.includes(l)?"bg-[#0d5b3a] text-white":"bg-[var(--soft)] text-[var(--green)]")}>{labels[l]}</button>)}</div></section>
 {error&&<div className="mt-5 rounded-xl border border-red-200 bg-red-50 px-4 py-3 text-sm text-red-700">{error}</div>}
 {loading?<div className="mt-6 grid gap-5 md:grid-cols-2">{[1,2,3,4,5,6].map(x=><div key={x} className="h-72 animate-pulse rounded-2xl bg-white"/>)}</div>:<div className="mt-6 grid gap-5 md:grid-cols-2"><MetricChart data={aggregate("visibility_score")} title="Visibility Score" format="percent"/><MetricChart data={aggregate("visibility_rank")} title="Visibility Rank"/><MetricChart data={aggregate("share_of_voice_score")} title="Share of Voice Score" format="percent"/><MetricChart data={aggregate("share_of_voice_rank")} title="Share of Voice Rank"/><MetricChart data={aggregate("average_position")} title="Average Position"/><MetricChart data={aggregate("average_position_rank")} title="Average Position Rank"/></div>}
 <section className="mt-8 platform-card overflow-hidden"><div className="platform-card-header"><h3 className="text-lg font-semibold">Answer Engine Snapshot</h3><p className="mt-1 text-sm text-[var(--muted-foreground)]">Latest visibility score for each selected provider.</p></div><div className="p-5"><h3 className="text-sm font-semibold">LLM latest values</h3><div className="mt-4 grid gap-3 md:grid-cols-2 xl:grid-cols-5">{LLMS.filter(l=>selectedLlms.includes(l)).map(l=>{const rs=filtered.filter(r=>r.llm_provider===l).sort((a,b)=>b.metric_date.localeCompare(a.metric_date));const r=rs[0];return <div key={l} className="rounded-xl border border-[var(--line)] bg-[var(--muted)] p-4"><div className="text-xs font-bold text-[#66736c]">{labels[l]}</div><div className="mt-2 text-2xl font-semibold">{r?.visibility_score!=null?r.visibility_score.toFixed(1)+"%":"—"}</div><div className="text-xs text-[#66736c]">visibility score</div></div>})}</div></div></section>
 </div></ProjectShell>}
