"use client";
import { useEffect,useMemo,useState } from "react";
import { ExternalLink,Filter } from "lucide-react";
import { useParams } from "next/navigation";
import { ProjectShell } from "@/components/project-shell";
import { supabase } from "@/lib/supabase";
type Row={metric_date:string;topic:string|null;llm_provider:string|null;url:string;page_name:string|null;brand_name:string|null;is_brand_related:boolean;frequency:number};
const LLMS=["chatgpt","gemini","perplexity","google_ai_overview","claude"],labels:Record<string,string>={chatgpt:"ChatGPT",gemini:"Gemini",perplexity:"Perplexity",google_ai_overview:"Google AI Overview",claude:"Claude"};
export default function CitationsPage(){
 const {projectId}=useParams<{projectId:string}>();const [rows,setRows]=useState<Row[]>([]),[topics,setTopics]=useState<string[]>([]),[topic,setTopic]=useState("All"),[llms,setLlms]=useState<string[]>([]),[period,setPeriod]=useState("Last 7 Days"),[loading,setLoading]=useState(true),[error,setError]=useState("");
 const start=useMemo(()=>{const d=new Date();d.setHours(0,0,0,0);const days=period==="Today"?0:period==="Last 2 Days"?1:period==="Last 14 Days"?13:period==="Last 30 Days"?29:period==="Last 90 Days"?89:period==="All Time"?3650:6;d.setDate(d.getDate()-days);return d.toISOString().slice(0,10)},[period]);
 useEffect(()=>{(async()=>{setLoading(true);const {data:p}=await supabase.from("projects").select("topics").eq("id",projectId).single();setTopics(p?.topics??[]);const {data,error}=await supabase.from("citations").select("metric_date,topic,llm_provider,url,page_name,brand_name,is_brand_related,frequency").eq("project_id",projectId).gte("metric_date",start).order("metric_date",{ascending:false});if(error)setError(error.message);setRows(data??[]);setLoading(false)})()},[projectId,start]);
 const filtered=rows.filter(r=>(topic==="All"||r.topic===topic)&&(llms.length===0||llms.includes(r.llm_provider||"")));
 const aggregate=(brandOnly:boolean)=>{const map=new Map<string,{url:string;page_name:string|null;brand_name:string|null;frequency:number}>();for(const r of filtered){if(r.is_brand_related!==brandOnly&&brandOnly)return;const old=map.get(r.url);map.set(r.url,{url:r.url,page_name:r.page_name,brand_name:r.brand_name,frequency:(old?.frequency??0)+r.frequency})}return [...map.values()].sort((a,b)=>b.frequency-a.frequency)};
 const Table=({title,data}:{title:string;data:ReturnType<typeof aggregate>})=><section className="rounded-3xl border border-[#d9ded9] bg-white p-6"><h3 className="text-lg font-semibold">{title}</h3><div className="mt-4 overflow-x-auto"><table className="w-full min-w-[760px] text-left text-sm"><thead><tr className="border-b border-[#d9ded9] text-xs uppercase tracking-[0.12em] text-[#66736c]"><th className="px-3 py-3">No.</th><th className="px-3 py-3">Page</th><th className="px-3 py-3">Page Name</th><th className="px-3 py-3">Brand Name</th><th className="px-3 py-3">Frequency</th></tr></thead><tbody>{data.map((r,i)=><tr key={r.url} className="border-b border-[#eef0ee]"><td className="px-3 py-3">{i+1}</td><td className="max-w-[380px] px-3 py-3"><a href={r.url} target="_blank" rel="noreferrer" className="inline-flex max-w-[360px] items-center gap-1 truncate font-semibold text-[#0d5b3a] hover:underline">{r.url}<ExternalLink size={13}/></a></td><td className="px-3 py-3">{r.page_name||"—"}</td><td className="px-3 py-3">{r.brand_name||"—"}</td><td className="px-3 py-3 font-semibold">{r.frequency}</td></tr>)}{!data.length&&<tr><td colSpan={5} className="px-3 py-10 text-center text-sm text-[#66736c]">No citations found.</td></tr>}</tbody></table></div></section>;
 return <ProjectShell><div className="mt-6"><p className="text-xs font-bold uppercase tracking-[0.22em] text-[#0d5b3a]">Citations</p><h2 className="mt-2 text-4xl font-semibold">Citation intelligence</h2><p className="mt-2 text-sm text-[#66736c]">Every cited page extracted from the tracked AI responses.</p>
 <div className="mt-6 rounded-2xl border border-[#d9ded9] bg-white p-4"><div className="flex flex-wrap gap-2"><Filter size={17} className="my-2 text-[#0d5b3a]"/>{["Today","Last 2 Days","Last 7 Days","Last 14 Days","Last 30 Days","Last 90 Days","All Time"].map(p=><button key={p} onClick={()=>setPeriod(p)} className={"rounded-xl border px-3 py-2 text-xs font-semibold "+(period===p?"border-[#0d5b3a] bg-[#0d5b3a] text-white":"border-[#d9ded9] bg-white")}>{p}</button>)}</div>
 <div className="mt-3 flex flex-wrap gap-2"><span className="py-1.5 text-xs font-bold text-[#66736c]">Topic:</span><button onClick={()=>setTopic("All")} className={"rounded-full px-3 py-1.5 text-xs font-semibold "+(topic==="All"?"bg-[#0d5b3a] text-white":"bg-[#eef4ef] text-[#0d5b3a]")}>All</button>{topics.map(t=><button key={t} onClick={()=>setTopic(t)} className={"rounded-full px-3 py-1.5 text-xs font-semibold "+(topic===t?"bg-[#0d5b3a] text-white":"bg-[#eef4ef] text-[#0d5b3a]")}>{t}</button>)}</div>
 <div className="mt-3 flex flex-wrap gap-2"><span className="py-1.5 text-xs font-bold text-[#66736c]">LLMs:</span>{LLMS.map(l=><button key={l} onClick={()=>setLlms(v=>v.includes(l)?v.filter(x=>x!==l):[...v,l])} className={"rounded-full px-3 py-1.5 text-xs font-semibold "+(llms.includes(l)?"bg-[#0d5b3a] text-white":"bg-[#eef4ef] text-[#0d5b3a]")}>{labels[l]}</button>)}</div></div>
 {error&&<div className="mt-5 rounded-xl border border-red-200 bg-red-50 px-4 py-3 text-sm text-red-700">{error}</div>}
 <div className="mt-6 space-y-5">{loading?<div className="h-80 animate-pulse rounded-3xl bg-white"/>:<><Table title="Brand-related Pages" data={aggregate(true)}/><Table title="All Cited Pages" data={aggregate(false).concat(aggregate(true)).sort((a,b)=>b.frequency-a.frequency).filter((x,i,a)=>a.findIndex(y=>y.url===x.url)===i)}/></>}</div>
 </div></ProjectShell>}
