"use client";
import { useEffect,useMemo,useState } from "react";
import { Filter } from "lucide-react";
import { useParams } from "next/navigation";
import { ProjectShell } from "@/components/project-shell";
import { supabase } from "@/lib/supabase";
type Row={metric_date:string;topic:string|null;llm_provider:string|null;brand_name:string;website:string|null;visibility_score:number|null;citation_count:number};
const LLMS=["chatgpt","gemini","perplexity","google_ai_overview","claude"],labels:Record<string,string>={chatgpt:"ChatGPT",gemini:"Gemini",perplexity:"Perplexity",google_ai_overview:"Google AI Overview",claude:"Claude"};
export default function CompetitorsPage(){
 const {projectId}=useParams<{projectId:string}>();const [rows,setRows]=useState<Row[]>([]),[topics,setTopics]=useState<string[]>([]),[topic,setTopic]=useState("All"),[llms,setLlms]=useState<string[]>([]),[period,setPeriod]=useState("Last 7 Days"),[loading,setLoading]=useState(true),[error,setError]=useState("");
 const start=useMemo(()=>{const d=new Date();d.setHours(0,0,0,0);const days=period==="Today"?0:period==="Last 2 Days"?1:period==="Last 14 Days"?13:period==="Last 30 Days"?29:period==="Last 90 Days"?89:period==="All Time"?3650:6;d.setDate(d.getDate()-days);return d.toISOString().slice(0,10)},[period]);
 useEffect(()=>{(async()=>{setLoading(true);const {data:p}=await supabase.from("projects").select("topics").eq("id",projectId).single();setTopics(p?.topics??[]);const {data,error}=await supabase.from("competitors").select("metric_date,topic,llm_provider,brand_name,website,visibility_score,citation_count").eq("project_id",projectId).gte("metric_date",start).order("metric_date",{ascending:false});if(error)setError(error.message);setRows(data??[]);setLoading(false)})()},[projectId,start]);
 const filtered=rows.filter(r=>(topic==="All"||r.topic===topic)&&(llms.length===0||llms.includes(r.llm_provider||"")));
 const agg=useMemo(()=>{const m=new Map<string,{brand_name:string;website:string|null;score:number[];citations:number}>();for(const r of filtered){const old=m.get(r.brand_name)||{brand_name:r.brand_name,website:r.website,score:[],citations:0};if(r.visibility_score!=null)old.score.push(r.visibility_score);old.citations+=r.citation_count;m.set(r.brand_name,old)}return [...m.values()].map(x=>({...x,visibility_score:x.score.length?x.score.reduce((a,b)=>a+b,0)/x.score.length:null})).sort((a,b)=>(b.visibility_score??-1)-(a.visibility_score??-1))},[filtered]);
 return <ProjectShell><div className="mt-1"><p className="page-eyebrow">Competitors</p><h2 className="page-title mt-1">Competitor landscape</h2><p className="page-description mt-2">Competitor brands extracted from tracked AI responses and ranked by visibility.</p>
 <div className="mt-6 rounded-2xl border border-[var(--line)] bg-white p-4"><div className="flex flex-wrap gap-2"><Filter size={17} className="my-2 text-[var(--green)]"/>{["Today","Last 2 Days","Last 7 Days","Last 14 Days","Last 30 Days","Last 90 Days","All Time"].map(p=><button key={p} onClick={()=>setPeriod(p)} className={"rounded-xl border px-3 py-2 text-xs font-semibold "+(period===p?"border-[#0d5b3a] bg-[#0d5b3a] text-white":"border-[var(--line)] bg-white")}>{p}</button>)}</div>
 <div className="mt-3 flex flex-wrap gap-2"><span className="py-1.5 text-xs font-bold text-[#66736c]">Topic:</span><button onClick={()=>setTopic("All")} className={"rounded-full px-3 py-1.5 text-xs font-semibold "+(topic==="All"?"bg-[#0d5b3a] text-white":"bg-[var(--soft)] text-[var(--green)]")}>All</button>{topics.map(t=><button key={t} onClick={()=>setTopic(t)} className={"rounded-full px-3 py-1.5 text-xs font-semibold "+(topic===t?"bg-[#0d5b3a] text-white":"bg-[var(--soft)] text-[var(--green)]")}>{t}</button>)}</div>
 <div className="mt-3 flex flex-wrap gap-2"><span className="py-1.5 text-xs font-bold text-[#66736c]">LLMs:</span>{LLMS.map(l=><button key={l} onClick={()=>setLlms(v=>v.includes(l)?v.filter(x=>x!==l):[...v,l])} className={"rounded-full px-3 py-1.5 text-xs font-semibold "+(llms.includes(l)?"bg-[#0d5b3a] text-white":"bg-[var(--soft)] text-[var(--green)]")}>{labels[l]}</button>)}</div></div>
 {error&&<div className="mt-5 rounded-xl border border-red-200 bg-red-50 px-4 py-3 text-sm text-red-700">{error}</div>}
 <section className="mt-6 rounded-2xl border border-[var(--line)] bg-white p-6"><div className="overflow-x-auto"><table className="platform-table min-w-[760px]"><thead><tr className="border-b border-[var(--line)] text-xs uppercase tracking-[0.12em] text-[#66736c]"><th className="px-3 py-3">No.</th><th className="px-3 py-3">Brand</th><th className="px-3 py-3">Website</th><th className="px-3 py-3">Visibility Score</th><th className="px-3 py-3">Number of Citations</th></tr></thead><tbody>{loading?<tr><td colSpan={5} className="px-3 py-10 text-center">Loading…</td></tr>:agg.map((r,i)=><tr key={r.brand_name} className="border-b border-[#eef0ee]"><td className="px-3 py-3">{i+1}</td><td className="px-3 py-3 font-semibold">{r.brand_name}</td><td className="px-3 py-3">{r.website?<a href={r.website} target="_blank" rel="noreferrer" className="text-[var(--green)] hover:underline">{r.website}</a>:"—"}</td><td className="px-3 py-3 font-semibold">{r.visibility_score!=null?r.visibility_score.toFixed(1)+"%":"—"}</td><td className="px-3 py-3">{r.citations}</td></tr>)}{!loading&&!agg.length&&<tr><td colSpan={5} className="px-3 py-10 text-center text-sm text-[#66736c]">No competitor data found for this period.</td></tr>}</tbody></table></div></section>
 </div></ProjectShell>}
