"use client";
import { ChangeEvent,useEffect,useState } from "react";
import { Download,Plus,Trash2,Upload,X } from "lucide-react";
import { useParams } from "next/navigation";
import * as XLSX from "xlsx";
import { ProjectShell,UserRole } from "@/components/project-shell";
import { supabase } from "@/lib/supabase";
type Prompt={id:string;prompt_number:number;prompt:string;topic:string;language:string;active:boolean};
const languages=["English","Malay","Chinese","Japanese","Korean","Thai","Indonesian","Arabic","Other"];
export default function PromptsPage(){
 const {projectId}=useParams<{projectId:string}>();const [prompts,setPrompts]=useState<Prompt[]>([]),[topics,setTopics]=useState<string[]>([]),[role,setRole]=useState<UserRole>("viewer"),[search,setSearch]=useState(""),[open,setOpen]=useState(false),[form,setForm]=useState({prompt:"",topic:"",language:"English"}),[busy,setBusy]=useState(false),[error,setError]=useState("");
 async function load(){const {data:{user}}=await supabase.auth.getUser();if(!user)return;const [{data:ps},{data:p},{data:profile},{data:m}]=await Promise.all([supabase.from("prompts").select("id,prompt_number,prompt,topic,language,active").eq("project_id",projectId).order("prompt_number"),supabase.from("projects").select("topics").eq("id",projectId).single(),supabase.from("profiles").select("role").eq("id",user.id).single(),supabase.from("project_members").select("role").eq("project_id",projectId).eq("user_id",user.id).maybeSingle()]);setPrompts(ps??[]);setTopics(p?.topics??[]);setRole(profile?.role==="superadmin"?"superadmin":m?.role??profile?.role??"viewer");}
 useEffect(()=>{load()},[projectId]);
 const canEdit=role!=="viewer";const filtered=prompts.filter(p=>p.prompt.toLowerCase().includes(search.toLowerCase())||p.topic.toLowerCase().includes(search.toLowerCase()));
 async function addPrompt(keepOpen=false){if(!form.prompt.trim()||!form.topic)return;if(prompts.length>=100){setError("The project already has 100 prompts.");return}setBusy(true);const n=Math.max(0,...prompts.map(p=>p.prompt_number))+1;const {error}=await supabase.from("prompts").insert({project_id:projectId,prompt_number:n,prompt:form.prompt.trim(),topic:form.topic,language:form.language});if(error)setError(error.message);else{setForm({prompt:"",topic:topics[0]||"",language:"English"});if(!keepOpen)setOpen(false);await load()}setBusy(false)}
 async function removePrompt(id:string){if(!confirm("Delete this prompt?"))return;const {error}=await supabase.from("prompts").delete().eq("id",id);if(error)setError(error.message);else load()}
 function template(){const ws=XLSX.utils.json_to_sheet([{Prompt:"Example prompt",Topic:topics[0]||"Example topic",Language:"English"}]);const wb=XLSX.utils.book_new();XLSX.utils.book_append_sheet(wb,ws,"Prompts");XLSX.writeFile(wb,"lifewood-prompts-template.xlsx")}
 async function upload(e:ChangeEvent<HTMLInputElement>){const file=e.target.files?.[0];if(!file)return;setBusy(true);setError("");try{const wb=XLSX.read(await file.arrayBuffer(),{type:"array"});const rows=XLSX.utils.sheet_to_json<Record<string,unknown>>(wb.Sheets[wb.SheetNames[0]]);if(prompts.length+rows.length>100)throw new Error("Bulk upload would exceed the 100-prompt limit.");const start=Math.max(0,...prompts.map(p=>p.prompt_number))+1;const payload=rows.map((r,i)=>({project_id:projectId,prompt_number:start+i,prompt:String(r.Prompt??r.prompt??"").trim(),topic:String(r.Topic??r.topic??"").trim(),language:String(r.Language??r.language??"").trim()})).filter(r=>r.prompt&&r.topic&&r.language);if(payload.length!==rows.length)throw new Error("Each row needs Prompt, Topic and Language.");const {error}=await supabase.from("prompts").insert(payload);if(error)throw error;await load()}catch(err){setError(err instanceof Error?err.message:String(err))}finally{setBusy(false);e.target.value=""}}
 return <ProjectShell><div className="ops-page"><div className="flex flex-col justify-between gap-4 lg:flex-row lg:items-end"><div><p className="page-eyebrow">Prompts</p><h2 className="page-title mt-1">Prompt library</h2><p className="page-description mt-2">Manage the 100 prompts used for daily AI visibility collection.</p></div>{canEdit&&<div className="flex flex-wrap gap-2"><button onClick={template} className="inline-flex items-center gap-2 platform-btn px-4 py-3 text-sm font-semibold"><Download size={16}/> Template</button><label className="inline-flex cursor-pointer items-center gap-2 platform-btn px-4 py-3 text-sm font-semibold"><Upload size={16}/> Bulk upload<input type="file" accept=".xlsx,.xls,.csv" className="hidden" onChange={upload}/></label><button disabled={prompts.length>=100} onClick={()=>{setForm({prompt:"",topic:topics[0]||"",language:"English"});setOpen(true)}} className="inline-flex items-center gap-2 platform-btn platform-btn-primary disabled:opacity-40"><Plus size={16}/> Add prompt</button></div>}</div>
 <div className="mt-6 grid gap-4 md:grid-cols-3"><div className="platform-card p-5"><div className="text-xs uppercase tracking-[.15em] text-[#66736c]">Prompts</div><div className="mt-2 text-4xl font-semibold">{prompts.length}<span className="text-lg text-[#66736c]"> / 100</span></div></div><div className="platform-card p-5"><div className="text-xs uppercase tracking-[.15em] text-[#66736c]">Remaining</div><div className="mt-2 text-4xl font-semibold">{100-prompts.length}</div></div><div className="platform-card p-5"><div className="text-xs uppercase tracking-[.15em] text-[#66736c]">Status</div><div className="mt-2 text-xl font-semibold">{prompts.length===100?"Ready":"Setup incomplete"}</div></div></div>
 {error&&<div className="mt-5 rounded-xl border border-red-200 bg-red-50 px-4 py-3 text-sm text-red-700">{error}</div>}
 <section className="mt-8 platform-card p-5"><div className="flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between"><h3 className="text-lg font-semibold">All prompts</h3><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search prompts…" className="platform-input text-sm"/></div><div className="mt-4 overflow-x-auto"><table className="platform-table min-w-[850px]"><thead><tr className="border-b border-[var(--line)] text-xs uppercase tracking-[.12em] text-[#66736c]"><th className="px-3 py-3">#</th><th className="px-3 py-3">Prompt</th><th className="px-3 py-3">Topic</th><th className="px-3 py-3">Language</th>{canEdit&&<th/>}</tr></thead><tbody>{filtered.map(p=><tr key={p.id} className="border-b border-[#eef0ee]"><td className="px-3 py-3">{p.prompt_number}</td><td className="max-w-[620px] px-3 py-3">{p.prompt}</td><td className="px-3 py-3"><span className="rounded-full bg-[var(--soft)] px-2.5 py-1 text-xs font-semibold text-[var(--green)]">{p.topic}</span></td><td className="px-3 py-3">{p.language}</td>{canEdit&&<td className="px-3 py-3 text-right"><button onClick={()=>removePrompt(p.id)} className="rounded-lg p-2 text-[#a13f35]"><Trash2 size={16}/></button></td>}</tr>)}{!filtered.length&&<tr><td colSpan={5} className="px-3 py-10 text-center text-sm text-[#66736c]">No prompts found.</td></tr>}</tbody></table></div></section>
 {open&&<div className="fixed inset-0 z-50 flex items-center justify-center bg-black/35 p-5"><div className="w-full max-w-xl rounded-3xl bg-white p-7"><div className="flex items-center justify-between"><h3 className="text-2xl font-semibold">Add prompt</h3><button onClick={()=>setOpen(false)}><X/></button></div><label className="mt-6 block text-sm font-semibold">Prompt<textarea rows={5} value={form.prompt} onChange={e=>setForm({...form,prompt:e.target.value})} className="mt-2 w-full platform-input"/></label><label className="mt-4 block text-sm font-semibold">Topic<select value={form.topic} onChange={e=>setForm({...form,topic:e.target.value})} className="mt-2 w-full platform-input">{topics.map(t=><option key={t}>{t}</option>)}</select></label><label className="mt-4 block text-sm font-semibold">Language<select value={form.language} onChange={e=>setForm({...form,language:e.target.value})} className="mt-2 w-full platform-input">{languages.map(l=><option key={l}>{l}</option>)}</select></label><div className="mt-6 flex justify-end gap-2"><button onClick={()=>setOpen(false)} className="platform-btn">Cancel</button><button disabled={busy||!form.prompt.trim()||!form.topic} onClick={()=>addPrompt(true)} className="rounded-xl border border-[#0d5b3a] px-4 py-3 text-sm font-semibold text-[var(--green)] disabled:opacity-40">Add & next</button><button disabled={busy||!form.prompt.trim()||!form.topic} onClick={()=>addPrompt(false)} className="platform-btn platform-btn-primary disabled:opacity-40">Add prompt</button></div></div></div>}
 </div></ProjectShell>}
