"use client";
import { useEffect,useState } from "react";
import { Check,Eye,EyeOff,Plus,Save,Trash2 } from "lucide-react";
import { useParams } from "next/navigation";
import { ProjectShell,UserRole } from "@/components/project-shell";
import { supabase } from "@/lib/supabase";
const providers=[["chatgpt","ChatGPT"],["gemini","Gemini"],["perplexity","Perplexity"],["google_ai_overview","Google AI Overview"],["claude","Claude"]] as const;
export default function SettingsPage(){
 const {projectId}=useParams<{projectId:string}>();const [role,setRole]=useState<UserRole>("viewer"),[brand,setBrand]=useState({brand_name:"",brand_description:"",brand_domains:"",brand_terms:"",brand_logo_url:""}),[topics,setTopics]=useState<string[]>([]),[newTopic,setNewTopic]=useState(""),[llms,setLlms]=useState<Record<string,{enabled:boolean;last4:string|null;key_updated_at:string|null}>>({}),[keys,setKeys]=useState<Record<string,string>>({}),[show,setShow]=useState<Record<string,boolean>>({}),[password,setPassword]=useState(""),[message,setMessage]=useState(""),[error,setError]=useState(""),[busy,setBusy]=useState(false);
 async function load(){const {data:{user}}=await supabase.auth.getUser();if(!user)return;const [{data:p},{data:profile},{data:m},{data:configs}]=await Promise.all([supabase.from("projects").select("brand_name,brand_description,brand_domains,brand_terms,brand_logo_url,topics").eq("id",projectId).single(),supabase.from("profiles").select("role").eq("id",user.id).single(),supabase.from("project_members").select("role").eq("project_id",projectId).eq("user_id",user.id).maybeSingle(),supabase.from("llm_configs").select("provider,enabled,api_key_last4,key_updated_at").eq("project_id",projectId)]);setRole(profile?.role==="superadmin"?"superadmin":m?.role??profile?.role??"viewer");if(p){setBrand({brand_name:p.brand_name,brand_description:p.brand_description||"",brand_domains:(p.brand_domains||[]).join("\n"),brand_terms:(p.brand_terms||[]).join("\n"),brand_logo_url:p.brand_logo_url||""});setTopics(p.topics||[])}const map:Record<string,{enabled:boolean;last4:string|null;key_updated_at:string|null}>={};for(const c of configs??[])map[c.provider]=c;setLlms(map)}
 useEffect(()=>{load()},[projectId]);
 const canEdit=role!=="viewer";
 async function saveBrand(){setBusy(true);setMessage("");setError("");const {error}=await supabase.from("projects").update({brand_name:brand.brand_name.trim(),brand_description:brand.brand_description.trim()||null,brand_domains:brand.brand_domains.split("\n").map(x=>x.trim()).filter(Boolean),brand_terms:brand.brand_terms.split("\n").map(x=>x.trim()).filter(Boolean),brand_logo_url:brand.brand_logo_url.trim()||null,topics}).eq("id",projectId);if(error)setError(error.message);else setMessage("Brand settings saved.");setBusy(false)}
 async function saveKey(provider:string){const key=keys[provider]?.trim();if(!key)return;setBusy(true);setMessage("");const {data,error}=await supabase.rpc("set_llm_api_key",{p_project_id:projectId,p_provider:provider,p_api_key:key});if(error)setError(error.message);else{setKeys(v=>({...v,[provider]:""}));setMessage(provider+" API key updated. Only the last four characters are shown.");await load()}setBusy(false)}
 async function removeKey(provider:string){if(!confirm("Remove this API key configuration?"))return;setBusy(true);const {error}=await supabase.rpc("remove_llm_api_key",{p_project_id:projectId,p_provider:provider});if(error)setError(error.message);else{setMessage("API key removed.");await load()}setBusy(false)}
 async function changePassword(){if(password.length<8){setError("Password must be at least 8 characters.");return}setBusy(true);const {error}=await supabase.auth.updateUser({password});if(error)setError(error.message);else{setPassword("");setMessage("Password updated.");}setBusy(false)}
 return <ProjectShell><div className="mt-6"><p className="text-xs font-bold uppercase tracking-[0.22em] text-[#0d5b3a]">Settings</p><h2 className="mt-2 text-4xl font-semibold">Project settings</h2><p className="mt-2 text-sm text-[#66736c]">Configure the brand, answer-engine connections and your account.</p>
 {message&&<div className="mt-5 flex items-center gap-2 rounded-xl border border-green-200 bg-green-50 px-4 py-3 text-sm text-green-800"><Check size={16}/>{message}</div>}{error&&<div className="mt-5 rounded-xl border border-red-200 bg-red-50 px-4 py-3 text-sm text-red-700">{error}</div>}
 <section className="mt-6 rounded-3xl border border-[#d9ded9] bg-white p-6"><h3 className="text-xl font-semibold">Brand Settings</h3><div className="mt-5 grid gap-5 lg:grid-cols-2"><label className="text-sm font-semibold">Brand name<input disabled={!canEdit} value={brand.brand_name} onChange={e=>setBrand({...brand,brand_name:e.target.value})} className="mt-2 w-full rounded-xl border border-[#d9ded9] px-4 py-3 disabled:bg-[#f6f3eb]"/></label><label className="text-sm font-semibold">Logo URL<input disabled={!canEdit} value={brand.brand_logo_url} onChange={e=>setBrand({...brand,brand_logo_url:e.target.value})} className="mt-2 w-full rounded-xl border border-[#d9ded9] px-4 py-3 disabled:bg-[#f6f3eb]"/></label><label className="text-sm font-semibold lg:col-span-2">Description<textarea disabled={!canEdit} rows={4} value={brand.brand_description} onChange={e=>setBrand({...brand,brand_description:e.target.value})} className="mt-2 w-full resize-none rounded-xl border border-[#d9ded9] px-4 py-3 disabled:bg-[#f6f3eb]"/></label><label className="text-sm font-semibold">Brand domains<span className="ml-1 font-normal text-[#66736c]">(one per line)</span><textarea disabled={!canEdit} rows={4} value={brand.brand_domains} onChange={e=>setBrand({...brand,brand_domains:e.target.value})} className="mt-2 w-full rounded-xl border border-[#d9ded9] px-4 py-3 disabled:bg-[#f6f3eb]"/></label><label className="text-sm font-semibold">Brand mention terms<span className="ml-1 font-normal text-[#66736c]">(one per line)</span><textarea disabled={!canEdit} rows={4} value={brand.brand_terms} onChange={e=>setBrand({...brand,brand_terms:e.target.value})} className="mt-2 w-full rounded-xl border border-[#d9ded9] px-4 py-3 disabled:bg-[#f6f3eb]"/></label></div><div className="mt-5"><div className="text-sm font-semibold">Topics</div><div className="mt-2 flex flex-wrap gap-2">{topics.map(t=><span key={t} className="inline-flex items-center gap-1 rounded-full bg-[#eef4ef] px-3 py-1.5 text-xs font-semibold text-[#0d5b3a]">{t}{canEdit&&<button onClick={()=>setTopics(v=>v.filter(x=>x!==t))}>×</button>}</span>)}</div>{canEdit&&<div className="mt-3 flex gap-2"><input value={newTopic} onChange={e=>setNewTopic(e.target.value)} placeholder="Add topic" className="rounded-xl border border-[#d9ded9] px-4 py-2.5 text-sm"/><button onClick={()=>{if(newTopic.trim()&&!topics.includes(newTopic.trim())){setTopics([...topics,newTopic.trim()]);setNewTopic("")}}} className="inline-flex items-center gap-2 rounded-xl border border-[#d9ded9] px-4 py-2.5 text-sm font-semibold"><Plus size={15}/> Add</button></div>}</div>{canEdit&&<button disabled={busy} onClick={saveBrand} className="mt-6 inline-flex items-center gap-2 rounded-xl bg-[#0d5b3a] px-4 py-3 text-sm font-semibold text-white"><Save size={16}/> Save brand settings</button>}</section>
 <section className="mt-6 rounded-3xl border border-[#d9ded9] bg-white p-6"><h3 className="text-xl font-semibold">LLM API Keys</h3><p className="mt-2 text-sm text-[#66736c]">Keys are never displayed after entry. The interface only shows the last four characters.</p><div className="mt-5 grid gap-4 lg:grid-cols-2">{providers.map(([id,label])=>{const c=llms[id];return <div key={id} className="rounded-2xl border border-[#e6eae6] p-5"><div className="flex items-center justify-between"><div><h4 className="font-semibold">{label}</h4><p className="mt-1 text-xs text-[#66736c]">{c?.enabled&&c.last4?"Configured · ••••"+c.last4:"Not configured"}</p></div>{c?.enabled&&<span className="rounded-full bg-[#eaf5ef] px-2.5 py-1 text-xs font-bold text-[#0d5b3a]">Active</span>}</div>{canEdit&&<div className="mt-4 flex gap-2"><div className="relative flex-1"><input type={show[id]?"text":"password"} value={keys[id]||""} onChange={e=>setKeys({...keys,[id]:e.target.value})} placeholder={c?.last4?"Enter a replacement key":"Paste API key"} className="w-full rounded-xl border border-[#d9ded9] px-4 py-2.5 pr-10 text-sm"/><button onClick={()=>setShow({...show,[id]:!show[id]})} className="absolute right-3 top-1/2 -translate-y-1/2 text-[#66736c]">{show[id]?<EyeOff size={16}/>:<Eye size={16}/>}</button></div><button onClick={()=>saveKey(id)} disabled={!keys[id]?.trim()||busy} className="rounded-xl bg-[#0d5b3a] px-4 py-2.5 text-sm font-semibold text-white disabled:opacity-40">Save</button>{c?.enabled&&<button onClick={()=>removeKey(id)} className="rounded-xl border border-red-200 px-3 py-2.5 text-[#a13f35]"><Trash2 size={16}/></button>}</div>}</div>})}</div></section>
 <section className="mt-6 rounded-3xl border border-[#d9ded9] bg-white p-6"><h3 className="text-xl font-semibold">Account Settings</h3><div className="mt-5 grid gap-4 md:grid-cols-2"><AccountField label="Registered name"/><AccountField label="Registered email"/></div><div className="mt-5 max-w-xl"><label className="text-sm font-semibold">New password<input type="password" value={password} onChange={e=>setPassword(e.target.value)} placeholder="Minimum 8 characters" className="mt-2 w-full rounded-xl border border-[#d9ded9] px-4 py-3"/></label><button onClick={changePassword} disabled={busy||!password} className="mt-3 rounded-xl border border-[#d9ded9] px-4 py-3 text-sm font-semibold">Change password</button></div></section>
 </div></ProjectShell>
}
function AccountField({label}:{label:string}){const [value,setValue]=useState("Loading…");useEffect(()=>{supabase.auth.getUser().then(async({data:{user}})=>{if(label==="Registered email")setValue(user?.email||"—");else if(user){const {data}=await supabase.from("profiles").select("full_name").eq("id",user.id).single();setValue(data?.full_name||"—")}})},[label]);return <label className="text-sm font-semibold">{label}<input readOnly value={value} className="mt-2 w-full rounded-xl border border-[#d9ded9] bg-[#f6f3eb] px-4 py-3"/></label>}
